-- =====================================================================
-- Base FIPE ampliada.
--
-- Cobertura das marcas efetivamente negociadas no mercado brasileiro,
-- com os modelos de maior giro em revenda e suas versões comerciais.
-- Serve como ponto de partida: a rotina mensal de sincronização
-- sobrescreve e completa esta base.
--
-- Idempotente — pode rodar de novo sem duplicar nada.
-- =====================================================================

create temporary table _fipe (
  marca       text not null,
  modelo      text not null,
  versao      text not null,
  combustivel text not null
) on commit drop;

insert into _fipe (marca, modelo, versao, combustivel) values
  ('Audi', 'A3', 'Sedan 1.4 TFSI S tronic', 'Gasolina'),
  ('Audi', 'A3', 'Sportback 2.0 TFSI', 'Gasolina'),
  ('Audi', 'A4', '2.0 TFSI S tronic', 'Gasolina'),
  ('Audi', 'A4', 'Avant 2.0 TFSI', 'Gasolina'),
  ('Audi', 'A5', 'Sportback 2.0 TFSI', 'Gasolina'),
  ('Audi', 'Q3', '1.4 TFSI S tronic', 'Gasolina'),
  ('Audi', 'Q3', 'Sportback 2.0 TFSI Quattro', 'Gasolina'),
  ('Audi', 'Q5', '2.0 TFSI Quattro S tronic', 'Gasolina'),
  ('Audi', 'Q5', 'Sportback 2.0 TFSI', 'Gasolina'),
  ('Audi', 'Q7', '3.0 TFSI Quattro', 'Gasolina'),
  ('Audi', 'Q8', '3.0 TFSI Quattro', 'Gasolina'),
  ('Audi', 'e-tron', '55 Quattro', 'Elétrico'),
  ('BMW', 'Série 1', '118i Sport GP', 'Gasolina'),
  ('BMW', 'Série 1', '120i M Sport', 'Gasolina'),
  ('BMW', 'Série 3', '320i Sport GP', 'Gasolina'),
  ('BMW', 'Série 3', '330e M Sport', 'Híbrido'),
  ('BMW', 'Série 5', '530i M Sport', 'Gasolina'),
  ('BMW', 'X1', 'sDrive20i GP', 'Gasolina'),
  ('BMW', 'X1', 'xDrive25i M Sport', 'Gasolina'),
  ('BMW', 'X3', 'xDrive30i X Line', 'Gasolina'),
  ('BMW', 'X3', 'M40i', 'Gasolina'),
  ('BMW', 'X4', 'xDrive30i M Sport', 'Gasolina'),
  ('BMW', 'X5', 'xDrive45e M Sport', 'Híbrido'),
  ('BMW', 'X5', 'xDrive30d', 'Diesel'),
  ('BMW', 'X6', 'xDrive40i M Sport', 'Gasolina'),
  ('BYD', 'Dolphin', 'Mini GL', 'Elétrico'),
  ('BYD', 'Dolphin', 'Plus', 'Elétrico'),
  ('BYD', 'Seal', 'AWD Performance', 'Elétrico'),
  ('BYD', 'Song Plus', 'DM-i Premium', 'Híbrido'),
  ('BYD', 'Yuan Plus', 'GS', 'Elétrico'),
  ('BYD', 'Yuan Plus', 'GL', 'Elétrico'),
  ('BYD', 'King', 'DM-i GL', 'Híbrido'),
  ('BYD', 'Han', 'EV', 'Elétrico'),
  ('CAOA Chery', 'Tiggo 5X', '1.5 CVT', 'Flex'),
  ('CAOA Chery', 'Tiggo 5X', 'Pro 1.5 CVT', 'Flex'),
  ('CAOA Chery', 'Tiggo 7', 'Pro 1.5 Turbo CVT', 'Flex'),
  ('CAOA Chery', 'Tiggo 8', '1.6 Turbo DCT', 'Gasolina'),
  ('CAOA Chery', 'Tiggo 8', 'Pro Max 2.0 Turbo', 'Gasolina'),
  ('CAOA Chery', 'Arrizo 6', 'Pro 1.5 Turbo CVT', 'Flex'),
  ('Chevrolet', 'Onix', '1.0 Flex Manual', 'Flex'),
  ('Chevrolet', 'Onix', 'LT 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Onix', 'LTZ 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Onix', 'Premier 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Onix Plus', 'LT 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Onix Plus', 'Premier 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Tracker', '1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Tracker', 'LTZ 1.0 Turbo AT', 'Flex'),
  ('Chevrolet', 'Tracker', 'Premier 1.2 Turbo AT', 'Flex'),
  ('Chevrolet', 'Spin', '1.8 LT AT', 'Flex'),
  ('Chevrolet', 'Spin', '1.8 Premier AT', 'Flex'),
  ('Chevrolet', 'Spin', '1.8 Activ AT', 'Flex'),
  ('Chevrolet', 'S10', 'LTZ 2.8 Diesel 4x4 AT', 'Diesel'),
  ('Chevrolet', 'S10', 'High Country 2.8 Diesel 4x4', 'Diesel'),
  ('Chevrolet', 'S10', 'LS 2.8 Diesel 4x2', 'Diesel'),
  ('Chevrolet', 'Montana', 'LTZ 1.2 Turbo AT', 'Flex'),
  ('Chevrolet', 'Montana', 'Premier 1.2 Turbo AT', 'Flex'),
  ('Chevrolet', 'Cruze', 'LT 1.4 Turbo AT', 'Flex'),
  ('Chevrolet', 'Cruze', 'Premier 1.4 Turbo AT', 'Flex'),
  ('Chevrolet', 'Cruze', 'Sport6 LTZ 1.4 Turbo', 'Flex'),
  ('Chevrolet', 'Equinox', 'Premier 2.0 Turbo AWD', 'Gasolina'),
  ('Chevrolet', 'Equinox', 'LT 1.5 Turbo', 'Gasolina'),
  ('Chevrolet', 'Prisma', 'LT 1.4 Manual', 'Flex'),
  ('Chevrolet', 'Prisma', 'LTZ 1.4 AT', 'Flex'),
  ('Chevrolet', 'Cobalt', 'LTZ 1.8 AT', 'Flex'),
  ('Chevrolet', 'Cobalt', 'Elite 1.8 AT', 'Flex'),
  ('Chevrolet', 'Celta', 'LT 1.0', 'Flex'),
  ('Chevrolet', 'Classic', 'LS 1.0', 'Flex'),
  ('Chevrolet', 'Trailblazer', 'Premier 2.8 Diesel 4x4', 'Diesel'),
  ('Chrysler', '300C', '3.6 V6', 'Gasolina'),
  ('Chrysler', '300C', '5.7 V8 Hemi', 'Gasolina'),
  ('Chrysler', 'PT Cruiser', 'Limited 2.4', 'Gasolina'),
  ('Chrysler', 'Town & Country', 'Limited 3.6 V6', 'Gasolina'),
  ('Citroën', 'C3', 'Live 1.0', 'Flex'),
  ('Citroën', 'C3', 'Feel 1.0 Turbo AT', 'Flex'),
  ('Citroën', 'C3', 'Shine 1.0 Turbo AT', 'Flex'),
  ('Citroën', 'C4 Cactus', 'Feel 1.6 AT', 'Flex'),
  ('Citroën', 'C4 Cactus', 'Shine 1.6 THP AT', 'Flex'),
  ('Citroën', 'Aircross', 'Feel 1.6 AT', 'Flex'),
  ('Citroën', 'Aircross', 'Shine 1.6', 'Flex'),
  ('Citroën', 'C4 Lounge', 'Shine 1.6 THP AT', 'Gasolina'),
  ('Citroën', 'Basalt', 'Feel 1.0 Turbo AT', 'Flex'),
  ('Citroën', 'Basalt', 'Shine 1.0 Turbo AT', 'Flex'),
  ('Citroën', 'Jumpy', 'Cargo 1.6 HDi', 'Diesel'),
  ('Dodge', 'Journey', 'SXT 3.6 V6', 'Gasolina'),
  ('Dodge', 'Journey', 'RT 3.6 V6', 'Gasolina'),
  ('Dodge', 'Durango', 'Limited 3.6 V6', 'Gasolina'),
  ('Dodge', 'Dakota', 'Sport 3.9 V6', 'Gasolina'),
  ('Fiat', 'Argo', 'Drive 1.0', 'Flex'),
  ('Fiat', 'Argo', 'Drive 1.3 AT', 'Flex'),
  ('Fiat', 'Argo', 'Trekking 1.3 AT', 'Flex'),
  ('Fiat', 'Argo', 'HGT 1.8 AT', 'Flex'),
  ('Fiat', 'Cronos', 'Drive 1.3 AT', 'Flex'),
  ('Fiat', 'Cronos', 'Precision 1.8 AT', 'Flex'),
  ('Fiat', 'Mobi', 'Like 1.0', 'Flex'),
  ('Fiat', 'Mobi', 'Trekking 1.0', 'Flex'),
  ('Fiat', 'Pulse', 'Drive 1.3 AT', 'Flex'),
  ('Fiat', 'Pulse', 'Audace 1.0 Turbo AT', 'Flex'),
  ('Fiat', 'Pulse', 'Impetus 1.0 Turbo AT', 'Flex'),
  ('Fiat', 'Pulse', 'Abarth 1.3 Turbo', 'Flex'),
  ('Fiat', 'Fastback', 'Audace 1.0 Turbo AT', 'Flex'),
  ('Fiat', 'Fastback', 'Impetus 1.3 Turbo AT', 'Flex'),
  ('Fiat', 'Fastback', 'Limited Edition 1.3 Turbo', 'Flex'),
  ('Fiat', 'Strada', 'Endurance 1.4 CS', 'Flex'),
  ('Fiat', 'Strada', 'Freedom 1.3 CD', 'Flex'),
  ('Fiat', 'Strada', 'Volcano 1.3 CD AT', 'Flex'),
  ('Fiat', 'Strada', 'Ranch 1.3 CD AT', 'Flex'),
  ('Fiat', 'Toro', 'Endurance 1.3 Turbo AT', 'Flex'),
  ('Fiat', 'Toro', 'Freedom 1.3 Turbo AT', 'Flex'),
  ('Fiat', 'Toro', 'Volcano 2.0 Diesel 4x4', 'Diesel'),
  ('Fiat', 'Toro', 'Ranch 2.0 Diesel 4x4', 'Diesel'),
  ('Fiat', 'Uno', 'Way 1.0', 'Flex'),
  ('Fiat', 'Uno', 'Drive 1.0', 'Flex'),
  ('Fiat', 'Uno', 'Sporting 1.4', 'Flex'),
  ('Fiat', 'Palio', 'Attractive 1.0', 'Flex'),
  ('Fiat', 'Palio', 'Weekend Adventure 1.8', 'Flex'),
  ('Fiat', 'Siena', 'EL 1.4', 'Flex'),
  ('Fiat', 'Siena', 'Essence 1.6', 'Flex'),
  ('Fiat', 'Punto', 'Attractive 1.4', 'Flex'),
  ('Fiat', 'Punto', 'Essence 1.6', 'Flex'),
  ('Fiat', 'Fiorino', 'Endurance 1.4', 'Flex'),
  ('Fiat', 'Ducato', 'Cargo 2.3 Diesel', 'Diesel'),
  ('Fiat', 'Grand Siena', 'Attractive 1.4', 'Flex'),
  ('Fiat', 'Grand Siena', 'Essence 1.6 AT', 'Flex'),
  ('Ford', 'Ka', 'SE 1.0', 'Flex'),
  ('Ford', 'Ka', 'SE Plus 1.5 AT', 'Flex'),
  ('Ford', 'Ka', 'FreeStyle 1.5 AT', 'Flex'),
  ('Ford', 'Ka Sedan', 'SE 1.5 AT', 'Flex'),
  ('Ford', 'Ka Sedan', 'Titanium 1.5 AT', 'Flex'),
  ('Ford', 'EcoSport', 'SE 1.5 AT', 'Flex'),
  ('Ford', 'EcoSport', 'Freestyle 1.5 AT', 'Flex'),
  ('Ford', 'EcoSport', 'Storm 2.0 4WD AT', 'Flex'),
  ('Ford', 'Ranger', 'XLS 2.2 Diesel 4x4 AT', 'Diesel'),
  ('Ford', 'Ranger', 'XLT 3.2 Diesel 4x4 AT', 'Diesel'),
  ('Ford', 'Ranger', 'Limited 3.2 Diesel 4x4', 'Diesel'),
  ('Ford', 'Ranger', 'Raptor 2.0 Bi-Turbo', 'Diesel'),
  ('Ford', 'Territory', 'SEL 1.5 Turbo AT', 'Gasolina'),
  ('Ford', 'Territory', 'Titanium 1.5 Turbo AT', 'Gasolina'),
  ('Ford', 'Bronco Sport', 'Wildtrak 2.0 Turbo AWD', 'Gasolina'),
  ('Ford', 'Maverick', 'Lariat 2.0 Turbo AWD', 'Gasolina'),
  ('Ford', 'Fusion', 'SEL 2.0 Turbo AT', 'Gasolina'),
  ('Ford', 'Fusion', 'Titanium 2.0 AWD', 'Gasolina'),
  ('Ford', 'Focus', 'SE 1.6 AT', 'Flex'),
  ('Ford', 'Focus', 'Titanium 2.0 AT', 'Flex'),
  ('Ford', 'Fiesta', 'SE 1.6 AT', 'Flex'),
  ('Ford', 'Fiesta', 'Titanium 1.6 AT', 'Flex'),
  ('Ford', 'Edge', 'Limited 3.5 V6 AWD', 'Gasolina'),
  ('GWM', 'Haval H6', 'HEV2 1.5 Turbo', 'Híbrido'),
  ('GWM', 'Haval H6', 'PHEV19 1.5 Turbo', 'Híbrido'),
  ('GWM', 'Haval H6', 'GT PHEV', 'Híbrido'),
  ('GWM', 'Ora 03', 'Skin GT', 'Elétrico'),
  ('GWM', 'Ora 03', 'Skin', 'Elétrico'),
  ('GWM', 'Poer', 'P30 2.0 Diesel 4x4', 'Diesel'),
  ('Honda', 'Civic', 'LX 2.0 CVT', 'Flex'),
  ('Honda', 'Civic', 'EX 2.0 CVT', 'Flex'),
  ('Honda', 'Civic', 'EXL 2.0 CVT', 'Flex'),
  ('Honda', 'Civic', 'Touring 1.5 Turbo CVT', 'Gasolina'),
  ('Honda', 'Civic', 'Si 1.5 Turbo', 'Gasolina'),
  ('Honda', 'City', 'EX 1.5 CVT', 'Flex'),
  ('Honda', 'City', 'EXL 1.5 CVT', 'Flex'),
  ('Honda', 'City', 'Touring 1.5 CVT', 'Flex'),
  ('Honda', 'City Hatchback', 'EXL 1.5 CVT', 'Flex'),
  ('Honda', 'City Hatchback', 'Touring 1.5 CVT', 'Flex'),
  ('Honda', 'Fit', 'LX 1.5 CVT', 'Flex'),
  ('Honda', 'Fit', 'EX 1.5 CVT', 'Flex'),
  ('Honda', 'Fit', 'EXL 1.5 CVT', 'Flex'),
  ('Honda', 'HR-V', 'LX 1.8 CVT', 'Flex'),
  ('Honda', 'HR-V', 'EX 1.8 CVT', 'Flex'),
  ('Honda', 'HR-V', 'EXL 1.8 CVT', 'Flex'),
  ('Honda', 'HR-V', 'Touring 1.5 Turbo CVT', 'Gasolina'),
  ('Honda', 'HR-V', 'Advance 1.5 Turbo', 'Gasolina'),
  ('Honda', 'WR-V', 'EX 1.5 CVT', 'Flex'),
  ('Honda', 'WR-V', 'EXL 1.5 CVT', 'Flex'),
  ('Honda', 'CR-V', 'EXL 1.5 Turbo AWD', 'Gasolina'),
  ('Honda', 'CR-V', 'Touring 1.5 Turbo', 'Gasolina'),
  ('Honda', 'ZR-V', 'Advance 2.0 e:HEV', 'Híbrido'),
  ('Honda', 'Accord', 'EX 3.5 V6', 'Gasolina'),
  ('Honda', 'Accord', 'Advanced Hybrid', 'Híbrido'),
  ('Hyundai', 'HB20', 'Sense 1.0', 'Flex'),
  ('Hyundai', 'HB20', 'Comfort 1.0', 'Flex'),
  ('Hyundai', 'HB20', 'Vision 1.0', 'Flex'),
  ('Hyundai', 'HB20', 'Platinum 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'HB20', 'Limited 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'HB20S', 'Vision 1.0', 'Flex'),
  ('Hyundai', 'HB20S', 'Platinum 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'HB20S', 'Limited 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'Creta', 'Comfort 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'Creta', 'Limited 1.0 Turbo AT', 'Flex'),
  ('Hyundai', 'Creta', 'Platinum 2.0 AT', 'Flex'),
  ('Hyundai', 'Creta', 'N Line 1.0 Turbo', 'Flex'),
  ('Hyundai', 'Tucson', 'GLS 1.6 Turbo AT', 'Gasolina'),
  ('Hyundai', 'Tucson', 'Limited 1.6 Turbo', 'Gasolina'),
  ('Hyundai', 'ix35', 'GL 2.0 AT', 'Flex'),
  ('Hyundai', 'ix35', 'Launching Edition 2.0', 'Flex'),
  ('Hyundai', 'Santa Fe', '3.3 V6 AWD', 'Gasolina'),
  ('Hyundai', 'Azera', '3.3 V6 AT', 'Gasolina'),
  ('Hyundai', 'Elantra', '2.0 AT', 'Gasolina'),
  ('Hyundai', 'i30', '2.0 AT', 'Gasolina'),
  ('Hyundai', 'Kona', 'Electric', 'Elétrico'),
  ('JAC', 'J3', '1.4 Manual', 'Gasolina'),
  ('JAC', 'T40', '1.5 AT', 'Gasolina'),
  ('JAC', 'T50', '1.5 AT', 'Gasolina'),
  ('JAC', 'E-JS1', 'Elétrico', 'Elétrico'),
  ('Jaguar', 'F-Pace', 'R-Sport 2.0 AWD', 'Gasolina'),
  ('Jaguar', 'F-Pace', 'Prestige 2.0', 'Gasolina'),
  ('Jaguar', 'E-Pace', 'S 2.0 AWD', 'Gasolina'),
  ('Jaguar', 'XE', 'Prestige 2.0', 'Gasolina'),
  ('Jaguar', 'XF', 'Prestige 2.0', 'Gasolina'),
  ('Jeep', 'Renegade', 'Sport 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Renegade', 'Longitude 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Renegade', 'Limited 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Renegade', 'Trailhawk 2.0 Diesel 4x4', 'Diesel'),
  ('Jeep', 'Renegade', 'Willys 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Compass', 'Sport 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Compass', 'Longitude 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Compass', 'Limited 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Compass', 'Trailhawk 2.0 Diesel 4x4', 'Diesel'),
  ('Jeep', 'Compass', 'Série S 2.0 Diesel 4x4', 'Diesel'),
  ('Jeep', 'Commander', 'Limited 1.3 Turbo AT', 'Flex'),
  ('Jeep', 'Commander', 'Overland 2.0 Diesel 4x4', 'Diesel'),
  ('Jeep', 'Wrangler', 'Sport 2.0 Turbo 4x4', 'Gasolina'),
  ('Jeep', 'Wrangler', 'Rubicon 2.0 Turbo 4x4', 'Gasolina'),
  ('Jeep', 'Grand Cherokee', 'Limited 3.6 V6 4x4', 'Gasolina'),
  ('Jeep', 'Grand Cherokee', 'Overland 3.0 Diesel', 'Diesel'),
  ('Jeep', 'Gladiator', 'Rubicon 3.6 V6 4x4', 'Gasolina'),
  ('Kia', 'Sportage', 'EX 2.0 AT', 'Gasolina'),
  ('Kia', 'Sportage', 'LX 1.6 Turbo Hybrid', 'Híbrido'),
  ('Kia', 'Cerato', 'SX 1.6 AT', 'Gasolina'),
  ('Kia', 'Cerato', 'EX 2.0 AT', 'Gasolina'),
  ('Kia', 'Soul', 'EX 1.6 AT', 'Gasolina'),
  ('Kia', 'Picanto', 'EX 1.0 AT', 'Gasolina'),
  ('Kia', 'Sorento', 'EX 3.5 V6 AWD', 'Gasolina'),
  ('Kia', 'Stonic', 'EX 1.0 Turbo Hybrid', 'Híbrido'),
  ('Kia', 'Seltos', 'EX 1.6 AT', 'Gasolina'),
  ('Kia', 'Niro', 'EX Hybrid', 'Híbrido'),
  ('Land Rover', 'Range Rover Evoque', 'SE 2.0 AWD', 'Gasolina'),
  ('Land Rover', 'Range Rover Evoque', 'R-Dynamic SE 2.0', 'Gasolina'),
  ('Land Rover', 'Range Rover Evoque', 'Dynamic 2.0 Diesel', 'Diesel'),
  ('Land Rover', 'Discovery Sport', 'SE 2.0 AWD', 'Gasolina'),
  ('Land Rover', 'Discovery Sport', 'R-Dynamic 2.0 Diesel', 'Diesel'),
  ('Land Rover', 'Defender', '110 S 2.0 AWD', 'Gasolina'),
  ('Land Rover', 'Defender', '90 SE 3.0', 'Gasolina'),
  ('Land Rover', 'Range Rover Sport', 'HSE 3.0 V6', 'Diesel'),
  ('Land Rover', 'Freelander', '2 SE 2.2 Diesel', 'Diesel'),
  ('Land Rover', 'Discovery', 'HSE 3.0 V6 Diesel', 'Diesel'),
  ('Lexus', 'NX', '350h Luxury', 'Híbrido'),
  ('Lexus', 'RX', '350 F Sport', 'Gasolina'),
  ('Lexus', 'UX', '250h Dynamic', 'Híbrido'),
  ('Lexus', 'ES', '300h Luxury', 'Híbrido'),
  ('Mercedes-Benz', 'Classe A', '200 Advance', 'Gasolina'),
  ('Mercedes-Benz', 'Classe A', '250 Sport', 'Gasolina'),
  ('Mercedes-Benz', 'Classe A', '200 Sedan Advance', 'Gasolina'),
  ('Mercedes-Benz', 'Classe C', '180 Avantgarde', 'Gasolina'),
  ('Mercedes-Benz', 'Classe C', '200 EQ Boost', 'Híbrido'),
  ('Mercedes-Benz', 'Classe C', '300 AMG Line', 'Gasolina'),
  ('Mercedes-Benz', 'Classe E', '250 Avantgarde', 'Gasolina'),
  ('Mercedes-Benz', 'Classe E', '350 AMG Line', 'Gasolina'),
  ('Mercedes-Benz', 'GLA', '200 Advance', 'Gasolina'),
  ('Mercedes-Benz', 'GLA', '250 AMG Line', 'Gasolina'),
  ('Mercedes-Benz', 'GLB', '200 Progressive', 'Gasolina'),
  ('Mercedes-Benz', 'GLC', '220d 4Matic', 'Diesel'),
  ('Mercedes-Benz', 'GLC', '300 AMG Line', 'Gasolina'),
  ('Mercedes-Benz', 'GLE', '400d 4Matic', 'Diesel'),
  ('Mercedes-Benz', 'Sprinter', '416 Furgão', 'Diesel'),
  ('Mercedes-Benz', 'Sprinter', '515 Chassi', 'Diesel'),
  ('Mini', 'Cooper', 'S 2.0 Turbo', 'Gasolina'),
  ('Mini', 'Cooper', '3 Portas 1.5 Turbo', 'Gasolina'),
  ('Mini', 'Countryman', 'S All4 2.0', 'Gasolina'),
  ('Mini', 'Clubman', 'S 2.0 Turbo', 'Gasolina'),
  ('Mitsubishi', 'L200 Triton', 'Sport HPE 2.4 Diesel 4x4', 'Diesel'),
  ('Mitsubishi', 'L200 Triton', 'Sport HPE-S 2.4 Diesel', 'Diesel'),
  ('Mitsubishi', 'L200 Triton', 'Savana 2.4 Diesel 4x4', 'Diesel'),
  ('Mitsubishi', 'Pajero', 'Full 3.2 Diesel 4x4', 'Diesel'),
  ('Mitsubishi', 'Pajero', 'TR4 2.0 4x4', 'Flex'),
  ('Mitsubishi', 'Pajero Sport', 'HPE 2.4 Diesel 4x4', 'Diesel'),
  ('Mitsubishi', 'ASX', 'HPE 2.0 CVT', 'Gasolina'),
  ('Mitsubishi', 'Outlander', 'HPE-S 3.0 V6', 'Gasolina'),
  ('Mitsubishi', 'Outlander', 'PHEV', 'Híbrido'),
  ('Mitsubishi', 'Eclipse Cross', 'HPE-S 1.5 Turbo', 'Gasolina'),
  ('Mitsubishi', 'Lancer', '2.0 CVT', 'Gasolina'),
  ('Nissan', 'Kicks', 'S 1.6 CVT', 'Flex'),
  ('Nissan', 'Kicks', 'Sense 1.6 CVT', 'Flex'),
  ('Nissan', 'Kicks', 'Advance 1.6 CVT', 'Flex'),
  ('Nissan', 'Kicks', 'Exclusive 1.6 CVT', 'Flex'),
  ('Nissan', 'Versa', 'Sense 1.6 CVT', 'Flex'),
  ('Nissan', 'Versa', 'Advance 1.6 CVT', 'Flex'),
  ('Nissan', 'Versa', 'Exclusive 1.6 CVT', 'Flex'),
  ('Nissan', 'March', 'S 1.0', 'Flex'),
  ('Nissan', 'March', 'SV 1.6', 'Flex'),
  ('Nissan', 'Sentra', 'SV 2.0 CVT', 'Flex'),
  ('Nissan', 'Sentra', 'Exclusive 2.0 CVT', 'Flex'),
  ('Nissan', 'Frontier', 'Attack 2.3 Diesel 4x4', 'Diesel'),
  ('Nissan', 'Frontier', 'XE 2.3 Diesel 4x4', 'Diesel'),
  ('Nissan', 'Frontier', 'Pro-4X 2.3 Diesel', 'Diesel'),
  ('Nissan', 'Livina', 'SL 1.8 AT', 'Flex'),
  ('Nissan', 'Leaf', 'Elétrico', 'Elétrico'),
  ('Peugeot', '208', 'Like 1.0', 'Flex'),
  ('Peugeot', '208', 'Active 1.6 AT', 'Flex'),
  ('Peugeot', '208', 'Allure 1.0 Turbo AT', 'Flex'),
  ('Peugeot', '208', 'Griffe 1.0 Turbo AT', 'Flex'),
  ('Peugeot', '2008', 'Active 1.6 AT', 'Flex'),
  ('Peugeot', '2008', 'Allure 1.0 Turbo AT', 'Flex'),
  ('Peugeot', '2008', 'Griffe 1.0 Turbo AT', 'Flex'),
  ('Peugeot', '3008', 'Griffe 1.6 THP AT', 'Gasolina'),
  ('Peugeot', '5008', 'Griffe 1.6 THP AT', 'Gasolina'),
  ('Peugeot', '308', 'Allure 1.6 THP', 'Gasolina'),
  ('Peugeot', 'Partner', 'Furgão 1.6', 'Flex'),
  ('Peugeot', 'Expert', 'Cargo 1.6 HDi', 'Diesel'),
  ('Porsche', 'Macan', '2.0 Turbo', 'Gasolina'),
  ('Porsche', 'Macan', 'S 3.0 V6', 'Gasolina'),
  ('Porsche', 'Cayenne', '3.0 V6', 'Gasolina'),
  ('Porsche', 'Cayenne', 'S 2.9 V6', 'Gasolina'),
  ('Porsche', '911', 'Carrera 3.0', 'Gasolina'),
  ('Porsche', '911', 'Carrera S 3.0', 'Gasolina'),
  ('Porsche', 'Panamera', '4 2.9 V6', 'Gasolina'),
  ('Porsche', 'Boxster', '718 2.0', 'Gasolina'),
  ('Porsche', 'Taycan', '4S', 'Elétrico'),
  ('RAM', 'Rampage', 'Rebel 2.0 Turbo Diesel', 'Diesel'),
  ('RAM', 'Rampage', 'Laramie 2.0 Turbo Diesel', 'Diesel'),
  ('RAM', 'Rampage', 'R/T 2.0 Turbo', 'Gasolina'),
  ('RAM', '1500', 'Laramie 5.7 V8', 'Gasolina'),
  ('RAM', '1500', 'Rebel 5.7 V8', 'Gasolina'),
  ('RAM', '2500', 'Laramie 6.7 Diesel', 'Diesel'),
  ('RAM', '3500', 'Laramie 6.7 Diesel', 'Diesel'),
  ('RAM', 'Classic', 'Laramie 5.7 V8', 'Gasolina'),
  ('Renault', 'Kwid', 'Zen 1.0', 'Flex'),
  ('Renault', 'Kwid', 'Intense 1.0', 'Flex'),
  ('Renault', 'Kwid', 'Outsider 1.0', 'Flex'),
  ('Renault', 'Kwid', 'E-Tech', 'Elétrico'),
  ('Renault', 'Sandero', 'Life 1.0', 'Flex'),
  ('Renault', 'Sandero', 'Zen 1.0', 'Flex'),
  ('Renault', 'Sandero', 'Intense 1.6 CVT', 'Flex'),
  ('Renault', 'Logan', 'Zen 1.0', 'Flex'),
  ('Renault', 'Logan', 'Intense 1.6 CVT', 'Flex'),
  ('Renault', 'Duster', 'Intense 1.6 CVT', 'Flex'),
  ('Renault', 'Duster', 'Iconic 1.3 Turbo CVT', 'Flex'),
  ('Renault', 'Duster', 'Zen 1.6', 'Flex'),
  ('Renault', 'Captur', 'Intense 1.6 CVT', 'Flex'),
  ('Renault', 'Captur', 'Iconic 1.3 Turbo CVT', 'Flex'),
  ('Renault', 'Oroch', 'Intense 1.6', 'Flex'),
  ('Renault', 'Oroch', 'Outsider 1.3 Turbo CVT', 'Flex'),
  ('Renault', 'Stepway', 'Zen 1.6 CVT', 'Flex'),
  ('Renault', 'Stepway', 'Iconic 1.6 CVT', 'Flex'),
  ('Renault', 'Master', 'Furgão 2.3 Diesel', 'Diesel'),
  ('Renault', 'Master', 'Minibus 2.3 Diesel', 'Diesel'),
  ('Renault', 'Fluence', 'Dynamique 2.0 CVT', 'Flex'),
  ('Subaru', 'Forester', 'XT 2.0 Turbo AWD', 'Gasolina'),
  ('Subaru', 'Forester', 'S 2.0 AWD', 'Gasolina'),
  ('Subaru', 'XV', '2.0 AWD', 'Gasolina'),
  ('Subaru', 'Impreza', '2.0 AWD', 'Gasolina'),
  ('Subaru', 'Outback', '2.5 AWD', 'Gasolina'),
  ('Subaru', 'WRX', 'STI 2.5 Turbo', 'Gasolina'),
  ('Suzuki', 'Jimny', 'Sierra 1.5 4x4', 'Gasolina'),
  ('Suzuki', 'Jimny', '4Sport 1.3 4x4', 'Gasolina'),
  ('Suzuki', 'Vitara', '4You 1.6 4x4', 'Gasolina'),
  ('Suzuki', 'S-Cross', '4Style 1.4 Turbo', 'Gasolina'),
  ('Toyota', 'Corolla', 'GLi 1.8 CVT', 'Flex'),
  ('Toyota', 'Corolla', 'XEi 2.0 CVT', 'Flex'),
  ('Toyota', 'Corolla', 'Altis 2.0 CVT', 'Flex'),
  ('Toyota', 'Corolla', 'Altis Hybrid 1.8', 'Híbrido'),
  ('Toyota', 'Corolla', 'Altis Premium Hybrid 1.8', 'Híbrido'),
  ('Toyota', 'Corolla', 'GR-Sport 2.0 CVT', 'Flex'),
  ('Toyota', 'Corolla Cross', 'XR 2.0 CVT', 'Flex'),
  ('Toyota', 'Corolla Cross', 'XRE 2.0 CVT', 'Flex'),
  ('Toyota', 'Corolla Cross', 'XRX Hybrid 1.8', 'Híbrido'),
  ('Toyota', 'Corolla Cross', 'GR-Sport Hybrid 1.8', 'Híbrido'),
  ('Toyota', 'Hilux', 'SR 2.8 Diesel 4x4 AT', 'Diesel'),
  ('Toyota', 'Hilux', 'SRV 2.8 Diesel 4x4 AT', 'Diesel'),
  ('Toyota', 'Hilux', 'SRX 2.8 Diesel 4x4 AT', 'Diesel'),
  ('Toyota', 'Hilux', 'GR-Sport 2.8 Diesel 4x4', 'Diesel'),
  ('Toyota', 'Hilux', 'SRX Plus 2.8 Diesel', 'Diesel'),
  ('Toyota', 'Yaris', 'XL 1.3 AT', 'Flex'),
  ('Toyota', 'Yaris', 'XLS 1.5 CVT', 'Flex'),
  ('Toyota', 'Yaris', 'XS 1.5 CVT', 'Flex'),
  ('Toyota', 'Yaris Sedan', 'XL Plus 1.5 CVT', 'Flex'),
  ('Toyota', 'Yaris Sedan', 'XLS 1.5 CVT', 'Flex'),
  ('Toyota', 'SW4', 'SRX 2.8 Diesel 4x4 7L', 'Diesel'),
  ('Toyota', 'SW4', 'Diamond 2.8 Diesel 4x4', 'Diesel'),
  ('Toyota', 'SW4', 'SRV 2.8 Diesel 4x4', 'Diesel'),
  ('Toyota', 'RAV4', 'SX Hybrid AWD', 'Híbrido'),
  ('Toyota', 'RAV4', 'S Hybrid Connect', 'Híbrido'),
  ('Toyota', 'Etios', 'X 1.3', 'Flex'),
  ('Toyota', 'Etios', 'XLS 1.5', 'Flex'),
  ('Toyota', 'Etios', 'Sedan XLS 1.5', 'Flex'),
  ('Toyota', 'Camry', 'XLE 3.5 V6', 'Gasolina'),
  ('Toyota', 'Prius', 'Hybrid 1.8', 'Híbrido'),
  ('Troller', 'T4', '3.2 Diesel 4x4', 'Diesel'),
  ('Troller', 'T4', 'XLT 3.2 Diesel 4x4', 'Diesel'),
  ('Volkswagen', 'Gol', '1.0 MPI', 'Flex'),
  ('Volkswagen', 'Gol', '1.6 MSI AT', 'Flex'),
  ('Volkswagen', 'Gol', 'Last Edition 1.0', 'Flex'),
  ('Volkswagen', 'Polo', 'Track 1.0', 'Flex'),
  ('Volkswagen', 'Polo', 'Sense 1.0 Turbo AT', 'Flex'),
  ('Volkswagen', 'Polo', 'Highline 200 TSI AT', 'Flex'),
  ('Volkswagen', 'Polo', 'GTS 250 TSI AT', 'Flex'),
  ('Volkswagen', 'Virtus', 'Sense 1.0 Turbo AT', 'Flex'),
  ('Volkswagen', 'Virtus', 'Highline 200 TSI AT', 'Flex'),
  ('Volkswagen', 'Virtus', 'Exclusive 250 TSI AT', 'Flex'),
  ('Volkswagen', 'Virtus', 'GTS 250 TSI AT', 'Flex'),
  ('Volkswagen', 'T-Cross', '200 TSI AT', 'Flex'),
  ('Volkswagen', 'T-Cross', 'Comfortline 200 TSI AT', 'Flex'),
  ('Volkswagen', 'T-Cross', 'Highline 250 TSI AT', 'Flex'),
  ('Volkswagen', 'T-Cross', 'Sense 200 TSI', 'Flex'),
  ('Volkswagen', 'Nivus', 'Comfortline 200 TSI AT', 'Flex'),
  ('Volkswagen', 'Nivus', 'Highline 200 TSI AT', 'Flex'),
  ('Volkswagen', 'Nivus', 'Sense 200 TSI AT', 'Flex'),
  ('Volkswagen', 'Taos', 'Comfortline 250 TSI AT', 'Gasolina'),
  ('Volkswagen', 'Taos', 'Highline 250 TSI AT', 'Gasolina'),
  ('Volkswagen', 'Saveiro', 'Robust 1.6 CS', 'Flex'),
  ('Volkswagen', 'Saveiro', 'Cross 1.6 CD AT', 'Flex'),
  ('Volkswagen', 'Saveiro', 'Trendline 1.6 CS', 'Flex'),
  ('Volkswagen', 'Amarok', 'Highline 3.0 V6 Diesel 4x4', 'Diesel'),
  ('Volkswagen', 'Amarok', 'Extreme 3.0 V6 Diesel', 'Diesel'),
  ('Volkswagen', 'Amarok', 'Trendline 2.0 Diesel 4x4', 'Diesel'),
  ('Volkswagen', 'Jetta', 'Comfortline 250 TSI AT', 'Gasolina'),
  ('Volkswagen', 'Jetta', 'GLI 350 TSI AT', 'Gasolina'),
  ('Volkswagen', 'Tiguan', 'Allspace Comfortline 250 TSI', 'Gasolina'),
  ('Volkswagen', 'Tiguan', 'Allspace R-Line 350 TSI', 'Gasolina'),
  ('Volkswagen', 'Voyage', 'Trendline 1.6 AT', 'Flex'),
  ('Volkswagen', 'Voyage', 'Comfortline 1.6', 'Flex'),
  ('Volkswagen', 'Fox', 'Connect 1.6', 'Flex'),
  ('Volkswagen', 'Fox', 'Xtreme 1.6', 'Flex'),
  ('Volkswagen', 'Up', 'Move 1.0 TSI', 'Flex'),
  ('Volkswagen', 'Up', 'Cross 1.0 TSI', 'Flex'),
  ('Volkswagen', 'Golf', 'Comfortline 1.4 TSI AT', 'Gasolina'),
  ('Volkswagen', 'Golf', 'GTI 2.0 TSI', 'Gasolina'),
  ('Volkswagen', 'Golf', 'Highline 1.4 TSI', 'Gasolina'),
  ('Volkswagen', 'Passat', 'Highline 2.0 TSI', 'Gasolina'),
  ('Volvo', 'XC40', 'T4 Momentum', 'Gasolina'),
  ('Volvo', 'XC40', 'Recharge Pure Electric', 'Elétrico'),
  ('Volvo', 'XC40', 'R-Design T5', 'Gasolina'),
  ('Volvo', 'XC60', 'T5 Momentum AWD', 'Gasolina'),
  ('Volvo', 'XC60', 'T8 Inscription Recharge', 'Híbrido'),
  ('Volvo', 'XC90', 'T8 Inscription Recharge', 'Híbrido'),
  ('Volvo', 'S60', 'T4 Momentum', 'Gasolina'),
  ('Volvo', 'S60', 'T8 Polestar', 'Híbrido'),
  ('Volvo', 'C40', 'Recharge Twin Pure Electric', 'Elétrico');

insert into public.marcas (nome)
select distinct marca from _fipe
on conflict (nome) do nothing;

insert into public.modelos (marca_id, nome)
select distinct ma.id, f.modelo
from _fipe f
join public.marcas ma on ma.nome = f.marca
on conflict (marca_id, nome) do nothing;

insert into public.versoes (modelo_id, nome, combustivel)
select distinct mo.id, f.versao, f.combustivel
from _fipe f
join public.marcas  ma on ma.nome = f.marca
join public.modelos mo on mo.marca_id = ma.id and mo.nome = f.modelo
on conflict (modelo_id, nome) do nothing;
